const test = require('node:test');
const assert = require('node:assert/strict');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
process.env.NODE_ENV = 'development';
process.env.PORT = '0';
const { app, start } = require('../secure-server');

let server;
const storeFile = path.join(__dirname, '..', 'data/store.json');
const originalStore = fs.readFileSync(storeFile);
function request(method, url, body, headers = {}) { return new Promise((resolve, reject) => { const data = body ? JSON.stringify(body) : ''; const req = http.request(`http://127.0.0.1:${server.address().port}${url}`, { method, headers: { ...(body ? { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(data) } : {}), ...headers } }, res => { let output = ''; res.on('data', chunk => output += chunk); res.on('end', () => resolve({ status: res.statusCode, headers: res.headers, body: output ? JSON.parse(output) : null })); }); req.on('error', reject); req.end(data); }); }
test.before(async () => { server = await start(); });
test.after(() => { server.close(); fs.writeFileSync(storeFile, originalStore); });
test('rejects client total and price tampering while pricing from catalog', async () => { const result = await request('POST', '/api/orders', { customer: { name: 'Test Buyer', email: 'test@example.com', phone: '0700000000', address: 'Kampala', city: 'Kampala' }, items: [{ id: 1, qty: 1, price: 1 }], total: 1 }); assert.equal(result.status, 201); assert.equal(result.body.total, 185000); assert.notEqual(result.body.total, 1); });
test('requires tracking token and returns no customer PII', async () => { const created = await request('POST', '/api/orders', { customer: { name: 'Private Buyer', email: 'private@example.com', phone: '0700000000', address: 'Kampala', city: 'Kampala' }, items: [{ id: 2, qty: 1 }] }); const denied = await request('GET', `/api/orders/${created.body.id}`); assert.equal(denied.status, 403); const allowed = await request('GET', `/api/orders/${created.body.id}?token=${created.body.trackingToken}`); assert.equal(allowed.status, 200); assert.equal(allowed.body.customer, undefined); });
test('creates pending order in local mode when payment credentials are absent', async () => { const result = await request('POST', '/api/orders', { customer: { name: 'Dev Buyer', email: 'dev@example.com', phone: '0700000000', address: 'Kampala', city: 'Kampala' }, items: [{ id: 3, qty: 1 }] }); assert.equal(result.body.paymentStatus, 'Dev pending'); assert.equal(result.body.status, 'Pending'); });
test('production config fails closed', () => { const { assertProductionConfig } = require('../lib/config'); assert.throws(() => assertProductionConfig({ production: true, jwtSecret: 'weak', adminEmail: '', adminPassword: '', databaseUrl: '', paymentConfigured: false }), /Production configuration invalid/); });
test('admin CRUD manages reviews and public API exposes approved reviews only', async () => { const login = await request('POST', '/api/admin/login', { email: 'admin@auragems.test', password: 'ChangeMe123!' }); assert.equal(login.status, 200); const cookie = login.headers['set-cookie'][0].split(';')[0]; const invalid = await request('POST', '/api/admin/reviews', { name: 'A', text: 'A', rating: 6, approved: false }, { Cookie: cookie }); assert.equal(invalid.status, 400); const created = await request('POST', '/api/admin/reviews', { name: '<Admin>', text: '<Great>', rating: 5, approved: false }, { Cookie: cookie }); assert.equal(created.status, 201); const hidden = await request('GET', '/api/store'); assert.equal(hidden.body.reviews.some(review => review.id === created.body.id), false); const updated = await request('PUT', `/api/admin/reviews/${created.body.id}`, { name: '<Admin>', text: '<Great>', rating: 4, approved: true }, { Cookie: cookie }); assert.equal(updated.body.approved, true); const publicReviews = await request('GET', '/api/store'); assert.equal(publicReviews.body.reviews.some(review => review.id === created.body.id), true); const removed = await request('DELETE', `/api/admin/reviews/${created.body.id}`, undefined, { Cookie: cookie }); assert.equal(removed.status, 200); });
